export const RoulettePackets = {
    LOGIN: 'LOGIN',
    CURRENCIES: 'CURRENCIES',
    PLAY: 'PLAY',
    COLLECT: 'COLLECT',
    GAMBLE_PLAY: 'GAMBLE_PLAY',
    JACKPOTS: 'JACKPOTS',
    ERROR: 'ERROR',
    STATISTICS: 'STATISTICS',
    HISTORY: 'HISTORY'
}