export const AppConst = {
    GAME_CONTAINER: null,
    EMIT_RESIZE: "resize",
    BASE_PATH: "",
    ASSETS_LOADED: "assets_loaded",

    P_VIEW_MAIN: "P_VIEW_MAIN",
    W_GAMBLE: "W_GAMBLE",
    W_FREE_GAME: "W_FREE_GAME",
    W_PAY: "W_PAY",
    W_WARNING: "W_WARNING",
    W_SOUND: "W_SOUND",
    W_LANGUAGE: "W_LANGUAGE",
    W_BET_SETTINGS: "W_BET_SETTINGS",
    W_BONUS: "W_BONUS",
    W_FREE_GAME_BEGIN: "W_FREE_GAME_BEGIN",
    W_FREE_GAME_END: "W_FREE_GAME_END",
    W_FREE_IN_FREE: "W_FREE_IN_FREE",
    W_BUY_FREE: "W_BUY_FREE",
    W_INTRO: "W_INTRO",
    W_INTRO_INFO: "W_INTRO_INFO",
    W_HISTORY: "W_HISTORY",
    W_LOCALISATION: "W_LOCALISATION",
    W_MENU: "W_MENU",
    W_CALC: "W_CALC",
    W_REALITY: "W_REALITY",
    W_MOBILE_KEY: "W_MOBILE_KEY",
    W_SETTING: "W_SETTING",
    E_START_SHOW_WINDOW:"E_START_SHOW_WINDOW",
    E_START_HIDE_WINDOW:"E_START_HIDE_WINDOW",

    API_INIT: "INITIAL",
    API_SPIN: "SPIN",
    API_FREE_SPIN: "FREE_SPIN",
    API_RESPIN: "RESPIN",
    API_BET: "BET",
    API_COLLECT: "COLLECT",
    API_FREE_COLLECT: "FREE_COLLECT",
    API_GAMBLE_PLAY: "GAMBLE_PLAY",
    API_GAMBLE_END: "GAMBLE_END",
    API_GAMBLE_FREE_END: "GAMBLE_FREE_END",

    EMITSERVER_INIT: "init",
    EMITSERVER_SEND_SPIN: "sendSpin",
    EMITSERVER_ON_SPIN: "onSpin",
    EMITSERVER_SEND_COLLECT: "onSendCollect",
    EMITSERVER_PRESS_COLLECT: "pressCollect",
    EMITSERVER_COLLECT: "collect",
    EMITSERVER_GAMBLE: "gamble",
    EMITSERVER_HALF_COLLECT: "halfCollect",
    EMITSERVER_HISTORY: "history",

    PACKET_CREATE_DATA: "packet_create_data",

    WARNING_OTHER: 1,
    WARNING_NO_CASH: 2,
    WARNING_CONNECT_CLOSE: 3,
    WARNING_NO_INET_CLOSE: 4,
    WARNING_LOAD_ASSETS: 4,//14,
    WARNING_NO_INET: 5,
    WARNING_NO_CASH_FOR_BET: 6,
    WARNING_CUSTOM_WARNING: 7,
    WARNING_NEW_1: 8,//14,
    WARNING_NO_BET: 9,
    WARNING_LAST_WIN: 11,
    WARNING_AUTO_GAME: 12,
    WARNING_SERVER_MESSAGE: 13,
    CUSTOM_WARNING_ID: {
        "GENERAL_CODE": 1,
        "UNKNOWN": 1,
        "TECHNICAL_ERROR": 1,
        "WAGER_NOT_FOUND": 1,
        "OPERATION_NOT_ALLOWED": 1,
        "NOT_LOGGED_ON": 1,
        "AUTHENTICATION_FAILED": 1,
        "OUT_OF_MONEY_CODE": 1006,
        "UNKNOWN_CURRENCY": 1007,
        "PARAMETER_REQUIRED": 1,
        "BET_LIMIT_EXCEEDED": 1019,
        "ACCOUNT_BLOCKED": 1,
        "OUT_OF_ATTEMPTS": 1,
    },
    APP_WARNING_NO_INET: "warningNoInet",

    C_NONE: 0,
    C_PLAY: 1,
    C_WIN: 2,
    C_PLAY_GAMBLE: 3,
    C_AUTO_GAME: 4,
    C_START_FREE_GAME: 5,
    C_FREE_GAME: 6,
    C_END_FREE_GAME: 7,
    C_PLAY_GAMBLE_WAIT: 8,
    C_NONE_HOLD: 9,
    C_BLOCK: 10,
    C_RESPIN: 12,
    C_MENU_MOBILE: 13,
    C_PAYTABLE: 14,
    C_COLLECT: 15,
    C_BET_SETTINGS: 16,
    C_START_BONUS_GAME: 17,
    C_BONUS_GAME: 18,
    C_END_BONUS_GAME: 19,

    APP_EMIT_ON_WIN: "onWin",
    APP_EMIT_ON_BET: "onBet",
    APP_EMIT_ON_COINS: "onCoin",
    APP_EMIT_ON_CREDIT: "onCredit",
    APP_EMIT_CATCH_SCATTER: "catchScatter",
    APP_EMIT_STOP_REEL: "stopReel",
    APP_EMIT_STOP_EASE_REEL: "stopEaseReel",
    APP_EMIT_STOP_ALL_EASE_REEL: "stopAllEaseReel",
    APP_EMIT_SPIN_REEL: "sendSpin",
    APP_EMIT_SKIP_REEL: "skipReel",
    APP_EMIT_WIN_JACKPOT: "winJackpot",
    APP_EMIT_END_JACKPOT: "endJackpot",
    APP_EMIT_UPDATE_JACKPOT: "updateJackpot",
    APP_SHOW_LINE: "showLine",
    APP_SOUND_MUTE: "soundMute",
    APP_TOGGLE_SOUND: "toggleSound",
    APP_ON_TURBO: "onTurboActive",
    APP_WAIT_REEL: "waitReel",
    APP_GAMBLE_LOSE: "gambleLose",

    APP_AUTO_UPDATE_SPINS_COUNT: "onUpdateSpinsCount",
    APP_AUTO_COUNT_SPIN: "onupcountautospin",
    APP_AUTO_STOP: "onStopAuto",
    APP_AUTO_TOGGLE_BLOCK: "toggleAutoBlock",
    APP_AUTO_HIDE_BLOCK: "hideAutoBlock",
    APP_AUTO_PANEL: "autoPanelEmit",

    APP_MENU_DESK_TOGGLE: "togleDeskMenu",

    APP_EMIT_SKIP_WIN: "skipWinEffect",
    APP_EMIT_SKIP_SPIN: "skipSpinReel",
    APP_EMIT_SKIP_BLOCK: "skipBlockButton",
    APP_DEFAULT_STATE: "defState",
    APP_SHOW_WIN: "showWin",
    APP_START_INC_WIN: "showStartIncWin",
    APP_WIN_PARTICLES: "winparticles",
    APP_STOP_WIN_PARTICLES: "stopWinparticles",
    APP_SHOW_MESSAGE_WIN: "showMessageWin",
    APP_HIDE_MESSAGE_WIN: "hideMessageWin",
    APP_SHOW_BIG_WIN: "showBigWin",
    APP_SHOW_EPIC_WIN: "showEpicWin",
    APP_SHOW_MEGA_WIN: "showMegaWin",
    APP_SHOW_SUPER_MEGA_WIN: "showSuperMegaWin",
    APP_SHOW_BONUS_WIN: "showBonusWin",
    APP_HIDE_WIN_EFFECT: "app_hide_win_effect",
    APP_HIDE_WIN_LINE_PANEL: "app_hide_win_line_panel",

    EMIT_FREE_GAME_BEGIN: "emit_free_game_begin",
    EMIT_FREE_GAME_CONTINUE: "emit_free_game_continue",
    EMIT_FREE_GAME_END: "emit_free_game_end",
    EMIT_MORE_FREE: "emit_more_free",
    EMIT_CAN_START_FREE: "emit_can_start_free",
    EMIT_NEXT_FREE: "emit_next_free",

    EMIT_RE_SPIN_BEGIN: "emit_re_spin_begin",
    EMIT_RE_SPIN_CONTINUE: "emit_re_spin_continue",
    EMIT_RE_SPIN_END: "emit_re_spin_end",

    APP_BONUS_WIN: "bonusWin",
    APP_BONUS_START: "bonusStart",
    APP_BONUS_END: "bonusEnd",
    APP_BONUS_CLOSE: "bonusClose",

    EMIT_WIN: "emit_win",
    EMIT_INC_INFO_LINE: "emit_inc_info_line",

    APP_REELBLOCK_START: "reel_block_start",
    APP_REELBLOCK_END: "reel_block_end",
    REEL_COMPLETE: "complete",
    REEL_INNER_END: "preEase",
    REEL_INNER_START: "innerStart",
    REEL_SPIN: "spin",
    REEL_BLUR: "spinBlur",
    REEL_STOP_SYMBOL: "stopSymbol",
    REEL_ALL_DROP: "reelalldrop",
    C_REEL_ONE_STOP: "reel_one_stop",
    EMIT_REEL_WAIT:"emit_reel_wait",
    EMIT_REEL_WAIT_OFF:"emit_reel_wait_off",

    APP_EMIT_HINT_DOWN: "hint_down",
    APP_EMIT_HINT_HIDE: "hint_hide",

    APP_EMIT_RICH_START: "richstart",
    APP_EMIT_RICH_END: "richend",
    APP_EMIT_RICH_UPDATE: "richupdate",
    APP_EMIT_FORCE_START: "richpanel",

    DROP_E_REEL_DROP: "dropereeldrop",
    DROP_E_REEL_FALL: "dropereelfall",
    DROP_E_REEL_CRASH: "dropereelcrash",

    SLOT_SYMBOL_NONE: 0,
    SLOT_SYMBOL_NO_WIN: 2,
    SLOT_SYMBOL_WIN: 3,
    SLOT_SYMBOL_HIDE: 4,
    SLOT_SYMBOL_BLUR: 5,

    T_GAME_SIMPLE: 0,
    T_GAME_DROP: 1,
    T_GAME_CRASH: 2,
};
